package com.mark.app.hjshop4a.ui.homepager.model;

import com.mark.app.hjshop4a.R;
import com.mark.app.hjshop4a.ui.business.consumecommit.model.Model;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by pc on 2018/6/8.
 */

public class RoleData {
   
    public List<CenterDataModel>  memberData(){
         List<CenterDataModel> dataModels =new ArrayList<>();
//        CenterDataModel data1 =new CenterDataModel();
//        data1.setImg(R.mipmap.gold_bean);
//        data1.setText(R.string.me_金豆消费);
//        data1.setOnclick("1-1-1");
//        dataModels.add(data1);
//        CenterDataModel data2 =new CenterDataModel();
//        data2.setImg(R.mipmap.onlinerecharge);
//        data2.setText(R.string.me_在线充值);
//        data2.setOnclick("1-1-2");
//        dataModels.add(data2);
        CenterDataModel data3 =new CenterDataModel();
        data3.setImg(R.mipmap.assets);
        data3.setText( R.string.me_资产明细);
        data3.setOnclick("1-1-3");
        dataModels.add(data3);
//        CenterDataModel data4 =new CenterDataModel();
//        data4.setImg(R.mipmap.bill);
//        data4.setText(R.string.me_会员账单);
//        data4.setOnclick("1-1-4");
//        dataModels.add(data4);
        CenterDataModel data5 =new CenterDataModel();
        data5.setImg(R.mipmap.bankcard);
        data5.setText(R.string.me_银行卡);
        data5.setOnclick("1-2-1");
        dataModels.add(data5);
        CenterDataModel data6 =new CenterDataModel();
        data6.setImg(R.mipmap.recommend);
        data6.setText(R.string.me_我的推荐);
        data6.setOnclick("1-2-2");
        dataModels.add(data6);
        CenterDataModel data7 =new CenterDataModel();
        data7.setImg(R.mipmap.agent);
        data7.setText(R.string.me_申请代理);
        data7.setOnclick("1-2-3");
        dataModels.add(data7);
//        CenterDataModel data8 =new CenterDataModel();
//        data8.setImg(R.mipmap.busniess);
//        data8.setText(R.string.me_申请商户);
//        data8.setOnclick("1-2-4");
//        dataModels.add(data8);
        return dataModels;
    }
    public List<CenterDataModel>  merchantData(){
        List<CenterDataModel> dataModels =new ArrayList<>();
//        CenterDataModel data1 =new CenterDataModel();
//        data1.setImg( R.mipmap.store);
//        data1.setText( R.string.me_线下报单);
//        data1.setOnclick("2-1-1");
//        dataModels.add(data1);
//        CenterDataModel data2 =new CenterDataModel();
//        data2.setImg(R.mipmap.order);
//        data2.setText(R.string.me_报单账单);
//        data2.setOnclick("2-1-2");
//        dataModels.add(data2);
//        CenterDataModel data3 =new CenterDataModel();
//        data3.setImg(R.mipmap.gold_bean);
//        data3.setText( R.string.me_金豆兑换);
//        data3.setOnclick("2-1-3");
//        dataModels.add(data3);
//        CenterDataModel data4 =new CenterDataModel();
//        data4.setImg(R.mipmap.busniessbill);
//        data4.setText(R.string.me_账单);
//        data4.setOnclick("2-1-4");
//        dataModels.add(data4);
        CenterDataModel data5 =new CenterDataModel();
        data5.setImg(R.mipmap.busniessinfo);
        data5.setText(R.string.me_商户信息);
        data5.setOnclick("2-2-1");
        dataModels.add(data5);
//        CenterDataModel data6 =new CenterDataModel();
//        data6.setImg(R.mipmap.onlinerecharge);
//        data6.setText(R.string.me_在线充值);
//        data6.setOnclick("2-2-2");
//        dataModels.add(data6);
//        CenterDataModel data7 =new CenterDataModel();
//        data7.setImg(R.mipmap.withdrawals);
//        data7.setText(R.string.me_余额提现);
//        data7.setOnclick("2-2-3");
//        dataModels.add(data7);
//        CenterDataModel data8 =new CenterDataModel();
//        data8.setImg(R.mipmap.zxing);
//        data8.setText(R.string.me_收豆二维码);
//        data8.setOnclick("2-2-4");
//        dataModels.add(data8);
        CenterDataModel data9 =new CenterDataModel();
        data9.setImg(R.mipmap.assetdetail);
        data9.setText(R.string.资产详情);
        data9.setOnclick("2-3-1");
        dataModels.add(data9);
//        CenterDataModel data10 =new CenterDataModel();
//        data10.setImg(R.mipmap.applicationrecord);
//        data10.setText(R.string.申请记录);
//        data10.setOnclick("2-3-2");
//        dataModels.add(data10);
        CenterDataModel data11 =new CenterDataModel();
        data11.setImg(R.mipmap.bankcard);
        data11.setText(R.string.银行卡);
        data11.setOnclick("2-3-3");
        dataModels.add(data11);
        CenterDataModel data12 =new CenterDataModel();
        data12.setImg(R.mipmap.recommend);
        data12.setText(R.string.我的推荐);
        data12.setOnclick("2-3-4");
        dataModels.add(data12);
        return dataModels;
    }
    public List<CenterDataModel> areaData(){
        List<CenterDataModel> dataModels =new ArrayList<>();
        CenterDataModel data1 =new CenterDataModel();
        data1.setImg( R.mipmap.store);
        data1.setText( R.string.me_区域商户);
        data1.setOnclick("3-1-1");
        dataModels.add(data1);
//        CenterDataModel data2 =new CenterDataModel();
//        data2.setImg(R.mipmap.busniess_audit);
//        data2.setText(R.string.me_商户申请);
//        data2.setOnclick("3-1-2");
//        dataModels.add(data2);
        CenterDataModel data3 =new CenterDataModel();
        data3.setImg(R.mipmap.achievement);
        data3.setText( R.string.me_代理业绩);
        data3.setOnclick("3-1-3");
        dataModels.add(data3);
//        CenterDataModel data4 =new CenterDataModel();
//        data4.setImg(R.mipmap.withdrawcash);
//        data4.setText(R.string.me_余额提现);
//        data4.setOnclick("3-1-4");
//        dataModels.add(data4);
//        CenterDataModel data5 =new CenterDataModel();
//        data5.setImg(R.mipmap.cashdetial);
//        data5.setText(R.string.me_提现记录);
//        data5.setOnclick("3-2-1");
//        dataModels.add(data5);
        CenterDataModel data6 =new CenterDataModel();
        data6.setImg(R.mipmap.profit);
        data6.setText(R.string.me_区域收益);
        data6.setOnclick("3-2-2");
        dataModels.add(data6);
//        CenterDataModel data7 =new CenterDataModel();
//        data7.setImg(R.mipmap.order_audit);
//        data7.setText(R.string.me_辖区报单审核);
//        data7.setOnclick("3-2-3");
//        dataModels.add(data7);
        CenterDataModel data8 =new CenterDataModel();
        data8.setImg(R.mipmap.bankcard);
        data8.setText(R.string.me_银行卡);
        data8.setOnclick("3-2-4");
        dataModels.add(data8);
        CenterDataModel data9 =new CenterDataModel();
        data9.setImg(R.mipmap.recommend);
        data9.setText(R.string.me_我的推荐);
        data9.setOnclick("3-3-1");
        dataModels.add(data9);
//        CenterDataModel data10 =new CenterDataModel();
//        data10.setImg(R.mipmap.applicationrecord);
//        data10.setText(R.string.申请记录);
//        data10.setOnclick("2-3-2");
//        dataModels.add(data10);
//        CenterDataModel data11 =new CenterDataModel();
//        data11.setImg(R.mipmap.bankcard);
//        data11.setText(R.string.银行卡);
//        data11.setOnclick("2-3-3");
//        dataModels.add(data11);
//        CenterDataModel data12 =new CenterDataModel();
//        data12.setImg(R.mipmap.recommend);
//        data12.setText(R.string.我的推荐);
//        data12.setOnclick("2-3-4");
//        dataModels.add(data12);
        return dataModels;
    }
    
    public List<CenterDataModel> provinceData(){
        List<CenterDataModel> dataModels =new ArrayList<>();
        CenterDataModel data1 =new CenterDataModel();
        data1.setImg( R.mipmap.city);
        data1.setText( R.string.me_区域城市);
        data1.setOnclick("4-1-1");
        dataModels.add(data1);
        CenterDataModel data2 =new CenterDataModel();
        data2.setImg(R.mipmap.profit);
        data2.setText(R.string.me_区域收益);
        data2.setOnclick("4-1-2");
        dataModels.add(data2);
//        CenterDataModel data3 =new CenterDataModel();
//        data3.setImg(R.mipmap.withdrawcash);
//        data3.setText( R.string.me_余额提现);
//        data3.setOnclick("4-1-3");
//        dataModels.add(data3);
//        CenterDataModel data4 =new CenterDataModel();
//        data4.setImg(R.mipmap.cashdetial);
//        data4.setText(R.string.me_提现记录);
//        data4.setOnclick("4-1-4");
//        dataModels.add(data4);
        CenterDataModel data5 =new CenterDataModel();
        data5.setImg(R.mipmap.bankcard);
        data5.setText(R.string.me_银行卡);
        data5.setOnclick("4-2-1");
        dataModels.add(data5);
        CenterDataModel data6 =new CenterDataModel();
        data6.setImg(R.mipmap.recommend);
        data6.setText(R.string.me_我的推荐);
        data6.setOnclick("4-2-2");
        dataModels.add(data6);
        CenterDataModel data7 =new CenterDataModel();
        data7.setImg(R.mipmap.achievement);
        data7.setText(R.string.me_代理业绩);
        data7.setOnclick("4-2-3");
        dataModels.add(data7);
//        CenterDataModel data8 =new CenterDataModel();
//        data8.setImg(R.mipmap.zxing);
//        data8.setText(R.string.me_收豆二维码);
//        data8.setOnclick("4-4-4");
//        dataModels.add(data8);
//        CenterDataModel data9 =new CenterDataModel();
//        data9.setImg(R.mipmap.assetdetail);
//        data9.setText(R.string.资产详情);
//        data9.setOnclick("4-3-1");
//        dataModels.add(data9);
//        CenterDataModel data10 =new CenterDataModel();
//        data10.setImg(R.mipmap.applicationrecord);
//        data10.setText(R.string.申请记录);
//        data10.setOnclick("4-3-2");
//        dataModels.add(data10);
//        CenterDataModel data11 =new CenterDataModel();
//        data11.setImg(R.mipmap.bankcard);
//        data11.setText(R.string.银行卡);
//        data11.setOnclick("4-3-3");
//        dataModels.add(data11);
//        CenterDataModel data12 =new CenterDataModel();
//        data12.setImg(R.mipmap.recommend);
//        data12.setText(R.string.我的推荐);
//        data12.setOnclick("4-3-4");
//        dataModels.add(data12);
        return dataModels;
    }
}
